### ISSUE TITLE
Problem building gtkbuilder2.f90 on Manjaro

### ISSUE THREAD

**Issue by jtappin** [jerryd/gtk-fortran#89] opened 2015-06-14 10:54 UTC
I've finally managed to sit down with gtk-fortran again for a bit. But while trying to build a clean checkout I get the error below, while building  `gtkbuilder.f90`

```
/data/software/GtkFortran/gtk2_new/examples/gtkbuilder2.f90:90:0:

   function button2clicked (widget, gdata ) result(ret)  bind(c)
 1
in pp_format, at pretty-print.c:614
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
examples/CMakeFiles/gtkbuilder2.dir/build.make:54: recipe for target 'examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o' failed
make[2]: *** [examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o] Error 1
CMakeFiles/Makefile2:741: recipe for target 'examples/CMakeFiles/gtkbuilder2.dir/all' failed
make[1]: *** [examples/CMakeFiles/gtkbuilder2.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm not sure if it is a problem with the source file -- I don't see an obvious problem; or with gfortran 5.1.0; or with the Arch/Manjaro builds thereof. Has anyone else found a problem or built OK with 5.1.0?

It also occurs in `gtkf-sketcher.f90` (at line 785).

**Comment by vmagnin** [comment] 2015-06-24 20:56
Hi James,
I am still with gfortran 4.9.2 and it compiles gtk-fortran without problem (see https://github.com/jerryd/gtk-fortran/issues/75). GCC 5 being a major release, it is possibly a bug in the compiler.

**Comment by jvdp1** [comment] 2015-12-27 21:19
Dear,

Did you find a solution for this error message? I got the same error message using gfortran 5.3.1 on a Fedora 23.

In advance thank you.

**Comment by vmagnin** [comment] 2016-01-10 22:12
With gfortran 5.2.1 (Kubuntu 15.10), I got the same error message. There was no problem when I was using 4.9.2.

By googling "in pp_format, at pretty-print.c:614", I have found similar problems:
https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1376

So it seems it is a bug in gfortran 5.x... Too bad it is still present in 5.3.

**Comment by vmagnin** [comment] 2016-02-29 11:31
After upgrading to Kubuntu 16.04beta1, I still have the same problem (gcc 5.3.1 20160225). But the GCC error message is more detailed:
```
Scanning dependencies of target gtkbuilder2
[ 61%] Building Fortran object examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o
‘
~/gtk-fortran/examples/gtkbuilder2.f90:90:0:

   function button2clicked (widget, gdata ) result(ret)  bind(c)
 1
in pp_format, at pretty-print.c:614
0xcdae87 pp_format(pretty_printer*, text_info*)
        ../../src/gcc/pretty-print.c:614
0x12aabca diagnostic_report_diagnostic(diagnostic_context*, diagnostic_info*)
        ../../src/gcc/diagnostic.c:862
0x12ab315 warning(int, char const*, ...)
        ../../src/gcc/diagnostic.c:1027
0xd0cfe9 decl_attributes(tree_node**, tree_node*, int)
        ../../src/gcc/attribs.c:456
0x645bd2 build_function_decl
        ../../src/gcc/fortran/trans-decl.c:2046
0x645a37 gfc_create_function_decl(gfc_namespace*, bool)
        ../../src/gcc/fortran/trans-decl.c:2687
0x62f40c gfc_generate_module_code(gfc_namespace*)
        ../../src/gcc/fortran/trans.c:2068
0xd2e2fa translate_all_program_units
        ../../src/gcc/fortran/parse.c:5393
0xd2e2fa gfc_parse_file()
        ../../src/gcc/fortran/parse.c:5603
0x11f51e5 gfc_be_parse_file
        ../../src/gcc/fortran/f95-lang.c:229
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
examples/CMakeFiles/gtkbuilder2.dir/build.make:54 : la recette pour la cible « examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o » a échouée
make[2]: *** [examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o] Erreur 1
CMakeFiles/Makefile2:739 : la recette pour la cible « examples/CMakeFiles/gtkbuilder2.dir/all » a échouée
make[1]: *** [examples/CMakeFiles/gtkbuilder2.dir/all] Erreur 2
Makefile:146 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```

**Comment by jerryd** [comment] 2016-02-29 18:59
On 02/29/2016 03:31 AM, vmagnin wrote:
> After upgrading to Kubuntu 16.04beta1, I still have the same problem (gcc 5.3.1
> 20160225). But the GCC error message is more detailed:
> 

Have you tried with gcc 6?  I want to see if this is a known regression.  It has
been way too long since I tried building any of this gtk, so patience please.

Cheers,

Jerry

**Comment by vmagnin** [comment] 2016-02-29 20:45
Hi Jerry, 
happy to read you !
The problem appeared with gcc 5 : 5.1.0, 5.2.1, 5.3.1.  I have not found gcc 6 yet in the Ubuntu 16.04beta1 repositories. I am not familiar with building gcc and I am not sure I would easily find the way to build gtk-fortran with CMake and gcc 6...

The instructions to build gtk-fortran are here:
https://github.com/jerryd/gtk-fortran/wiki/git-basics

Cheers,
Vincent

**Comment by jerryd** [comment] 2016-02-29 21:04
On 02/29/2016 12:45 PM, vmagnin wrote:
> Hi Jerry,
> happy to read you !
> The problem appeared with gcc 5 : 5.1.0, 5.2.1, 5.3.1. I have not found gcc 6
> yet in the Ubuntu 16.04beta1 repositories. I am not familiar with building gcc
> and I am not sure I would easily find the way to build gtk-fortran with CMake
> and gcc 6...
> 
> The instructions to build gtk-fortran are here:
> https://github.com/jerryd/gtk-fortran/wiki/git-basics
> 
> Cheers,
> Vincent
> 

OK, I build 6 all the time and I am currently doing development/maintenance on
gfortran so I will git the gtk stuff here and try a build.

Regards,

Jerry

**Comment by jerryd** [comment] 2016-03-01 02:22
I can confirm this is a regession in gcc/gfortran.  I will be checking with our team to see if it is a known or newly reported bug

**Comment by vmagnin** [comment] 2016-03-01 16:10
## A workaround to build gtk-fortran with gcc 5

Waiting for a gcc patch, what you can do (tested with the gtk3 branch) to build gtk-fortran with gcc 5 is to comment the lines 77 and 78 in the CMakeLists.txt file in the `examples` directory: gtkbuilder2 will not be built.

But the same gcc problem occurs with another file:
```
Scanning dependencies of target gtkf-sketcher
[ 90%] Building Fortran object sketcher/CMakeFiles/gtkf-sketcher.dir/gtkf-sketcher.f90.o
‘
~/gtk-fortran/sketcher/gtkf-sketcher.f90:785:0:

   subroutine default_options (widget, gdata ) bind(c)
 1
in pp_format, at pretty-print.c:614
```
You can comment the lines 33 and 34 in the CMakeLists.txt file in the `sketcher` directory: gtkf-sketcher will not be built.
Now everything is built, except these two files !

**Comment by jerryd** [comment] 2016-03-01 19:51
On 03/01/2016 08:10 AM, vmagnin wrote:
> 
>     A workaround to build gtk-fortran with gcc 5
> 
> Waiting for a gcc patch, what you can do (tested with the gtk3 branch) to build
> gtk-fortran with gcc 5 is to comment the lines 77 and 78 in the CMakeLists.txt
> file in the |examples| directory: gtkbuilder2 will not be built.
> 
> But the same gcc problem occurs with another file:
> 
> |Scanning dependencies of target gtkf-sketcher [ 90%] Building Fortran object
> sketcher/CMakeFiles/gtkf-sketcher.dir/gtkf-sketcher.f90.o ‘
> ~/gtk-fortran/sketcher/gtkf-sketcher.f90:785:0: subroutine default_options
> (widget, gdata ) bind(c) 1 in pp_format, at pretty-print.c:614 |
> 
> You can comment the lines 33 and 34 in the CMakeLists.txt file in the |sketcher|
> directory: gtkf-sketcher will not be built.
> Now everything is built, except these two files !
> 

This is helpful. There is a possibility that we are trying to issue a diagnostic
and the diagnostic machinery is missing information, so it fails. Thus it is
difficult to narrow down. I have gtbuilder2 set up by itself with just the
includes so I can start tracing gcc through gdb and hopefully see what is
happening.  The actual failure is in a gcc_assert.

Thanks,

Jerry

**Comment by jerryd** [comment] 2016-03-01 20:24
The problem goes away if I remove the "    !GCC$ ATTRIBUTES DLLEXPORT :: button2clicked "
on Linux. (in gtkbuilder2.f90)

**Comment by vmagnin** [comment] 2016-03-01 21:01
And the two files gtkbuilder2.f90 and gtkf-sketcher.f90 are the only two files in gtk-fortran containing that "!GCC$ ATTRIBUTES DLLEXPORT" directive.

**Comment by jerryd** [comment] 2016-03-01 22:12
This narrows thing down a lot. I will put together a proper bug report

**Comment by vmagnin** [comment] 2016-06-13 20:54
# A very simple workaround to build gtk-fortran with gcc 5

by typing `make --help`, I found a very simple solution to prevent the abortion of the make process when an example can not be built: `make -i`

So the commands are:
```bash
    mkdir build
    cd build
    cmake ..
    make -i
    sudo make install
```

Waiting for the gcc bug to be fixed, this is the simplest solution !

Vincent

**Comment by vmagnin** [comment] 2016-06-25 19:42
gfortran-4.8 and 4.9 yield such warnings but do not bug:
```
../../examples/gtkbuilder2.f90:90:0: warning: ‘dllexport’ attribute directive ignored [-Wattributes]
   function button2clicked (widget, gdata ) result(ret)  bind(c)
 ^
...
```

**Comment by vmagnin** [comment] 2016-07-01 21:22
You can also build gtkbuilder2.f90 and gtkf-sketcher.f90 by forcing CMake to use gfortran-4.8 or 4.9:
```bash
cmake -DCMAKE_Fortran_COMPILER:FILEPATH=`which gfortran-4.8` ..
```
But we now have a problem building the PLplot examples:
```
/hl_plplot8e.f90:40.6:

  use plplot_extra
      1
Fatal Error: Cannot read module file 'plplot_extra.mod' opened at (1), because it was created by a different version of GNU Fortran
```
This problem persists even after deleting and recreating the build directory.

**Comment by vmagnin** [comment] 2016-07-09 16:50
The bug is still present in gfortran 5.4.0, now available in Ubuntu 16.04.

**Comment by vmagnin** [comment] 2016-09-14 19:53
The bug is still present in gfortran 6.2.0

**Comment by vmagnin** [comment] 2016-09-14 19:54
The bug is still present in gfortran 6.2.0 under ubuntu 16.10beta 32bits.
The error message is exactly the same as with gfortran 5.3.1.

**Comment by vmagnin** [comment] 2016-09-14 19:56
The bug is still present in gfortran 6.2.0 under ubuntu 16.10beta 32bits.
The error message is exactly the same as with gfortran 5.3.1.

**Comment by cbcoutinho** [comment] 2016-10-15 22:58
I'm having the same issue with gfortran 6.2.1 on OpenSUSE Tumbleweed.

Setting `make -i` is a passable workaround

**Comment by vmagnin** [comment] 2018-01-15 14:28
Hi Jerry,

I can now build correctly gtk-fortran with my gtk3 development branch (not yet pushed) under Ubuntu 17.10 (gfortran 7.2.0): even gtkf-sketcher and gtkbuilder2 seems to run. I just have some _warnings_ of that kind:
```
[ 70%] Building Fortran object examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o
/home/vmagnin/Vincent IEMN/Interfaces graphiques/gtk-fortran/examples/gtkbuilder2.f90:90:0:
   function button2clicked (widget, gdata ) result(ret)  bind(c)
Warning: ‘dllexport’ attribute directive ignored [-Wattributes].
```
but they are built !

I will close the issue in some time after pushing my development branches.

**Closed** 2018-10-09 08:41 UTC
Labels: Bug
