### ISSUE TITLE
cmake seems to fail on master

### ISSUE THREAD

**Issue by jerryd** [jerryd/gtk-fortran#114] opened 2017-07-15 21:57 UTC
Following the instructions in the INSTALL file I am getting the following:
----- snip -----
    linked by target "mandelbrot" in directory /home/jerry/dev/gtk-fortran/examples
    linked by target "menu" in directory /home/jerry/dev/gtk-fortran/examples
    linked by target "notebooks" in directory /home/jerry/dev/gtk-fortran/examples
    linked by target "hl_pbar_p" in directory /home/jerry/dev/gtk-fortran/examples
    linked by target "gio_demo" in directory /home/jerry/dev/gtk-fortran/examples

-- Configuring incomplete, errors occurred!
I may have some time to help on this, so let me know.

**Comment by vmagnin** [comment] 2017-07-16 08:13
Hi Jerry,

I've got no error when building Master under Kubuntu 17.04 (CMake 3.7.2):
```
 mkdir build
 cd build
 cmake ..
 make -i
```
After looking on the web, it seems your CMake errors occur when a variable is not defined. Can you paste the whole error message ?

**Comment by jerryd** [comment] 2017-07-16 22:01
OK, I was missing a gtk-devel library so have that installed. Using FDedora 25 here so i get through the make with the following error whcih I think I have seen before:

[ 73%] Building Fortran object examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o
‘
/home/jerry/dev/gtk-fortran/examples/gtkbuilder2.f90:90:0:

   function button2clicked (widget, gdata ) result(ret)  bind(c)
 
in pp_format, at pretty-print.c:633
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
[ 74%] Linking Fortran executable gtkbuilder2
f95: error: CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o: No such file or directory
[ 74%] Built target gtkbuilder2

**Comment by vmagnin** [comment] 2017-07-17 10:20
Fine.
For the gtkbuilder2.f90 problem, see issue https://github.com/jerryd/gtk-fortran/issues/89

It occurs since GCC5, and you said it was a GCC regression. That's why we use make -i to ignore this building error.

My current gfortran version is:
GNU Fortran (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

**Comment by jerryd** [comment] 2017-07-29 20:21
Update on this. With Fedora 26, just updated, this issue goes away. So it must have been an upstream bug that has been fixed.

**Comment by vmagnin** [comment] 2017-07-30 19:43
Fine ! Fedora 26 uses gcc7. I Will wait Ubuntu 17.10 (coming also with gcc7) to test and close the issue 89.

**Closed** 2018-01-12 16:06 UTC
Labels: Discussion

**Comment by vmagnin** [comment] 2018-01-15 14:27
Hi Jerry,

I can now build correctly gtk-fortran with my gtk3 development branch (not yet pushed) under Ubuntu 17.10 (gfortran 7.2.0): even gtkf-sketcher and gtkbuilder2 seems to run. I just have some _warnings_ of that kind:
```
[ 70%] Building Fortran object examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o
/home/vmagnin/Vincent IEMN/Interfaces graphiques/gtk-fortran/examples/gtkbuilder2.f90:90:0:
   function button2clicked (widget, gdata ) result(ret)  bind(c)
Warning: ‘dllexport’ attribute directive ignored [-Wattributes].
```
but they are built !

I will close the issue in some time after pushing my development branches.
